### ISSUE TITLE
make all code .netstandard2.0 

### ISSUE THREAD

**Issue by pjmagee** [wingyplus/dagger-dotnet-sdk#11]
Why?

- the container may be able to run any .NET core version of the code, but from a user C# Developer point of view, when they try to compile,build the code locally they will want to use a version of the .NET SDk available to them on their machine, this may be restricted to LTS versions of the .NET SDK (or even older out of support). 

Most of the Source generated code and base code of the Dagger .NET API is using pretty standard .NET APIs, which are all mostly available in the .netstandard2.0 base library, any featues that are nice and only available in .NET8, such as newer LINQ functions etc, we can easily port across into our shared .netstandard2.0 Dagger.SDK

**Comment by wingyplus** [comment]
Agreed. 👍
