### ISSUE TITLE
Document how to run dotnet test when working on the SDK

### ISSUE THREAD

**Issue by pjmagee** [wingyplus/dagger-dotnet-sdk#17]
How can we automate 'dotnet test' so it works with Dagger and have correct SESSION + TOKEN?

Right now I am doing `dagger run dotnet test`. Is this the correct and right way to test? 

- Is there a way to run `dotnet /t:Dagger` and we then have a MSBuild Target which then runs `dagger run dotnet test`? 
- Can we hi-jack Dagger exe in Test Setup, and then get ENV Variable and then add this to the EnvVariables of the Test Process?

Mockup idea 1)

```
daggerProcess = Process.Start() // `dagger run [echo Env variables]; sleep 1000;
// This could be a bash/pwsh which echo variables to Stdout (and we take these and populate `.Port` and `.Token`

Environmment.SetEnvironmentVariable(daggerProcess.Port); // port
Environmment.SetEnvironmentVariable(daggerProcess.Token); // token
new GraphQLClient() // Will pickup variables and have access to dagger engine
daggerProcess.Dispose() // sigterm the process - which kill the sleep and dagger.exe will terminate
```

Mockup idea 2)

Can we use `dagger call test -dir ./sdk` and write go function which build and run the code in dagger engine... which then... has access to engine?? I feel like this wouldnt work, I am not familiar enough

**Comment by wingyplus** [comment]
I think `2`  would be better. We already have docker engine spin up as a service including dagger cli install inside the container in https://github.com/wingyplus/dagger-dotnet-sdk/blob/main/main.go#L22-L30. We can extract those lines to a new method and modify a bit to run against dotnet sdk image.

**Comment by wingyplus** [comment]
Instead of `-dir sdk`, you can use `dag.CurrentModule().Source()` to access root repository and use `Directory("sdk")` to accessing the sdk directory. :)
